# Generated by Django 5.2.8 on 2026-02-22 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removal_pending', 'Removal Pending'), ('removed', 'Removed'), ('unresolvable', 'Unresolvable'), ('disputed', 'Disputed'), ('false_positive', 'False Positive')], default='active', max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('data_fields', models.JSONField(blank=True, default=list, help_text="List of detected field names e.g. ['name', 'address', 'phone']")),
                ('is_visible', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('scan_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='scans.scantarget')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sources.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'matches',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_data', models.JSONField(default=dict)),
                ('page_text', models.TextField(blank=True)),
                ('is_still_live', models.BooleanField(default=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='matches.match')),
            ],
            options={
                'verbose_name': 'Match Snapshot',
                'verbose_name_plural': 'Match Snapshots',
                'db_table': 'match_snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='matches.match')),
            ],
            options={
                'verbose_name': 'Match Tag',
                'verbose_name_plural': 'Match Tags',
                'db_table': 'match_tags',
                'unique_together': {('match', 'tag')},
            },
        ),
    ]
