# Generated by Django 5.2.8 on 2026-02-22 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovalRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('escalated', 'Escalated'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('method', models.CharField(blank=True, help_text='Inherited from source removal template.', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_removals', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Removal Request',
                'verbose_name_plural': 'Removal Requests',
                'db_table': 'removal_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemovalLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('escalated', 'Escalated'), ('attempt_made', 'Attempt Made'), ('confirmed', 'Confirmed')], max_length=30)),
                ('message', models.TextField()),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='removals.removalrequest')),
            ],
            options={
                'verbose_name': 'Removal Log',
                'verbose_name_plural': 'Removal Logs',
                'db_table': 'removal_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemovalAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('method_used', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('is_success', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='removals.removalrequest')),
            ],
            options={
                'verbose_name': 'Removal Attempt',
                'verbose_name_plural': 'Removal Attempts',
                'db_table': 'removal_attempts',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
