# Generated by Django 5.2.8 on 2026-02-22 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Source Category',
                'verbose_name_plural': 'Source Categories',
                'db_table': 'source_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_automated', models.BooleanField(default=False, help_text='Whether removal can be automated.')),
                ('scraping_config', models.JSONField(blank=True, default=dict)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('avg_removal_days', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='sources.sourcecategory')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceRemovalTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('email', 'Email'), ('form', 'Web Form'), ('api', 'API'), ('manual', 'Manual')], max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('form_url', models.URLField(blank=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('template_body', models.TextField(blank=True, help_text='Email template or instructions.')),
                ('instructions', models.TextField(blank=True, help_text='Human-readable removal steps.')),
                ('expected_turnaround_days', models.PositiveIntegerField(default=30)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='removal_template', to='sources.source')),
            ],
            options={
                'verbose_name': 'Source Removal Template',
                'verbose_name_plural': 'Source Removal Templates',
                'db_table': 'source_removal_templates',
            },
        ),
    ]
