# Generated by Django 5.2.8 on 2026-02-22 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIdentity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Default', help_text='A friendly name for this identity.', max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of name variations.')),
                ('emails', models.JSONField(blank=True, default=list)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('addresses', models.JSONField(blank=True, default=list)),
                ('usernames', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Identity',
                'verbose_name_plural': 'Search Identities',
                'db_table': 'search_identities',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('partial', 'Partial Scan'), ('monitoring', 'Monitoring Scan')], default='full', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Completion percentage 0-100.')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sources_count', models.PositiveIntegerField(default=0)),
                ('matches_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='scans.searchidentity')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'db_table': 'scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_results', models.JSONField(blank=True, default=list)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='scans.scan')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_targets', to='sources.source')),
            ],
            options={
                'verbose_name': 'Scan Target',
                'verbose_name_plural': 'Scan Targets',
                'db_table': 'scan_targets',
                'unique_together': {('scan', 'source')},
            },
        ),
    ]
